#ifndef  RANDOM_NUMBER
#define  RANDOM_NUMBER

#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <curand_kernel.h>
#include "cuda_runtime.h"
#include <stdio.h>
#include "Structure.h"
#include <iostream>
#include <random>
#define randCut 1.0422679

/*Gauss random cut : a advanced method to simulate the polymer system,
	as a traditional gauss random number usually trends to break up the
	FENE bond. */
__device__ inline float2 uniform_random(int tid,
	curandState* dev_s)
{
	float2 s1;

	s1.x = curand_uniform(dev_s + tid);
	s1.y = curand_uniform(dev_s + tid);

	return s1;
}

__device__ inline float2 gauss_random_cut(int tid,
	curandState* dev_s)
{
	float2 s1;
	float mid[2];
	int i;

	for (i = 0; i < 2; i++)
	{
		mid[i] = curand_normal(dev_s + tid) * randCut;
		if (abs(mid[i]) > 2 * randCut)
		{
			if (mid[i] > 2 * randCut)
			{
				mid[i] = 2 * randCut;
			}
			else {
				mid[i] = -2 * randCut;
			}
		}
	}

	s1.x = mid[0];
	s1.y = mid[1];

	return s1;
}
/*Gauss random number generated by curand.h in three dimensions */
__device__ inline float2 gauss_random(int tid,
	curandState* dev_s)
{
	float2 s1;

	s1.x = curand_normal(dev_s + tid);
	s1.y = curand_normal(dev_s + tid);

	return s1;
}

__global__ void Device_set_seed(Particle colloid);

void Generate_Random_Number(Particle colloid);
/************************************************************************/
/* The rand number from host;                                           */
/************************************************************************/
inline void SetSeed(long int inputSeed)
{
	srand(inputSeed);
	//srand(time(NULL));
}

inline float Uniform()
{
	float t;
	t = rand() / (RAND_MAX + 1.0);
	return(t);
}

inline float Gauss1()
{
	int i;
	float mean = 0.0;
	float sigma = 1.0;
	float x, y;

	for (x = 0, i = 0; i < 12; i++) x += Uniform();
	x = x - 6;
	y = mean + x * sigma;

	return(y);
}

inline float Gauss2()
{
	float x1, x2, r2, fac;
	static int calc_new = 1;
	static float save;

	/* On every second call two gaussian random numbers are calculated
	   via the Box-Muller transformation. One is returned as the result
	   and the second one is stored for use on the next call.
	*/
	if (calc_new) {
		/* draw two uniform random numbers in the unit circle */
		do {
			x1 = 2.0 * Uniform() - 1.0;
			x2 = 2.0 * Uniform() - 1.0;
			r2 = x1 * x1 + x2 * x2;
		} while (r2 >= 1.0 || r2 == 0.0);
		/* perform Box-Muller transformation */
		fac = sqrtf(-2.0 * log(r2) / r2);
		/* save one number for later use */
		save = x1 * fac;
		calc_new = 0;
		/* return the second number */
		return x2 * fac;
	}
	else {
		calc_new = 1;
		/* return the stored gaussian random number */
		return save;

	}

}
/** Generator for Gaussian random numbers. Uses the Box-Muller
* transformation to generate two Gaussian random numbers from two
* uniform random numbers. which generates numbers between -2 sigma and
* 2 sigma in the form of a Gaussian with standard deviation sigma=1.118591404
* resulting in an actual standard deviation of 1.
*
* @return Gaussian random number.
*/
inline float GaussCut(void) {
	float x1, x2, r2, fac;
	static int calc_new = 1;
	static float save, curr;

	/* On every second call two gaussian random numbers are calculated
	   via the Box-Muller transformation. One is returned as the result
	   and the second one is stored for use on the next call.
	*/

	if (calc_new) {

		/* draw two uniform random numbers in the unit circle */
		do {
			x1 = 2.0 * Uniform() - 1.0;
			x2 = 2.0 * Uniform() - 1.0;
			r2 = x1 * x1 + x2 * x2;
		} while (r2 >= 1.0 || r2 == 0.0);

		/* perform Box-Muller transformation */
		fac = sqrtf(-2.0 * log(r2) / r2);

		// save one number for later use 
		save = x1 * fac * 1.042267973;
		if (fabs(save) > 2 * 1.042267973) {
			if (save > 0) save = 2 * 1.042267973;
			else save = -2 * 1.042267973;
		}
		calc_new = 0;

		// return the second number 
		curr = x2 * fac * 1.042267973;
		if (fabs(curr) > 2 * 1.042267973) {
			if (curr > 0) curr = 2 * 1.042267973;
			else curr = -2 * 1.042267973;
		}
		return curr;
	}
	else {
		calc_new = 1;
		/* return the stored gaussian random number */
		return save;

	}

}


#endif
